defaultAssertionDataset: poc_jetbrains
defaultLocation: EU
defaultProject: test-internal-368519
vars:
  GA4_DATASET: analytics_314592805
  LOCAL_TIMEZONE: Europe/Paris
  QUALITY_DATASET: poc_jetbrains
  TRANSFORMATIONS_DATASET: poc_jetbrains
  OUTPUTS_DATASET: poc_jetbrains