defaultAssertionDataset: ga4_dataform
defaultLocation: EU
defaultProject: ga4-export-349907
vars:
  GA4_DATASET: analytics_314592805
  LOCAL_TIMEZONE: Europe/Amsterdam
  QUALITY_DATASET: ga4_dataform
  TRANSFORMATIONS_DATASET: ga4_dataform
  OUTPUTS_DATASET: ga4_dataform
  LABEL_GENERIC_BRAND: superformlabs # constant 
  LABEL_GENERIC_TOOL: ga4dataform # constant for now... 
  LABEL_GENERIC_LICENSE_TYPE: core # core or premium 
  LABEL_EXECUTION_OPERATION: daily_workflow # daily_workflow or backfilling 
  LABEL_GENERIC_PACKAGE_VERSION: v1-17-0
