defaultAssertionDataset: ga4_dataform
defaultLocation: EU
defaultProject: ga4-export-349907
vars:
  GA4_DATASET: analytics_314592805
  LOCAL_TIMEZONE: Europe/Paris
  QUALITY_DATASET: ga4_dataform
  TRANSFORMATIONS_DATASET: ga4_dataform
  OUTPUTS_DATASET: ga4_dataform