defaultAssertionDataset: superform_assertion
defaultLocation: EU
defaultProject: dataform-package
vars:
  GA4_DATASET: analytics_314592805
  LOCAL_TIMEZONE: Europe/Paris
  QUALITY_DATASET: poc_jetbrains
  TRANSFORMATIONS_DATASET: poc_jetbrains
  OUTPUTS_DATASET: poc_jetbrains